### PR TITLE
Update amigo_iberico.md

### PR DESCRIPTION
**Pull request by tmcorreia**
Figure size and sidebar title

### CODE REVIEW

**Review by eurunuela — APPROVED** [review]
The changes look good @tmcorreia but I see no changes on the sidebar as you mention in the PR description. Do you want to add more changes to this PR or should I merge?

**Comment by tmcorreia** [comment]
> The changes look good @tmcorreia but I see no changes on the sidebar as you mention in the PR description. Do you want to add more changes to this PR or should I merge?

Didn't it change Amig@ Iberico to Amig@ Iberic@? That's all for now. I was just testing, thanks :)

**Comment by eurunuela** [comment]
> Didn't it change Amig@ Iberico to Amig@ Iberic@? That's all for now. I was just testing, thanks :)

No, you will have to edit `_includes/sidebar.html` for that.

**Comment by eurunuela** [comment]
Do you want me to take care of the sidebar @tmcorreia ?

**Comment by tmcorreia** [comment]
> Do you want me to take care of the sidebar @tmcorreia ?

I must be doing something wrong. Let's set a time next week and we get it all done at once :) I will message you on slack when I have the banner ready

**Pull request merged**
