### PR TITLE
Update committee.md

### PR DESCRIPTION
**Pull request by gabrll**
I updated the committee web page with new members.

### CODE REVIEW

**Review by eurunuela — CHANGES_REQUESTED** [review]
Hey Gabriel, thanks for opening the PR.

I don't think you've added the new image as part of this PR. I think you may want to do that before merging this.

**Comment by gabrll** [comment]
Hi Eneko,

Thanks for your comment. I'm not sure if I did it correctly, but I can see the image file in this branch. (folder assets/images)
"IBC_ExecMembers_2024.png"

Should it be also in main?

**Comment by eurunuela** [comment]
I don't see the file in the pull request. Did you add the file to your commit when you pushed?

**Review by eurunuela — APPROVED** [review]
I see the file was added directly into `main` without a pull request. That's why I couldn't see it as a change on this PR. I'm going to approve the changes so you can merge now. Next time though, it would be better to have a pull request for all related changes instead of directly merging one-out changes with `main`.

**Pull request merged**
